### ISSUE TITLE
Probability or score of named entities

### ISSUE THREAD

**Issue by kiran-surya** [attardi/deepnl#15]
Hi,

Can we get the score / probability for named entity tagging ?

**Comment by kiran-surya** [comment]
Hi,

Any updates on this ?

**Comment by attardi** [comment]
Do you mean the score for each individual tag in the sequence?
Take a look at method Tagger.tag() in tagger.pyx.
It computes the scores for all tags for the whole sequence:
   scores = self._tag_sequence(seq)
Then viterbi is applied to select the best path score, which determines which tags are returned.
The resulting list of tags might not correspond to the tags with highest score at each point in the sequence, since viterbi optimizes the overall path score.

**Comment by kiran-surya** [comment]
thank you.
